# This is a basic workflow to help you get started with Actions

name: check available house.

# Controls when the workflow will run
on:
  schedule:
    - cron: "*/10 * * * *" 
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  issues: write  # This line ensures the workflow has permission to create issues

jobs:
  call-callee:
    runs-on: ubuntu-latest
    steps:

      - name: Check time range
        run: |
          # Get the current hour in UTC
          HOUR=$(date +"%H")
          
          # Check if outside 8 AM to 10 PM UTC range
          if [ $HOUR -lt 8 ] || [ $HOUR -gt 22 ]; then
            echo "Current time is outside the schedule range. Exiting..."
            exit 0
          fi
          
          # If within range, the steps below will run

      - name: Call Callee Workflow
        uses: ./.github/workflows/target.yml
        with:
          param1: "Hello"
          param2: "World"