# This is a basic workflow to help you get started with Actions

name: check available house(2).

# Controls when the workflow will run
on:
  schedule:
    - cron: "*/10 * * * *" 
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  issues: write  # This line ensures the workflow has permission to create issues

jobs:
  check-time-range:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      # - uses: actions/checkout@v3
      - name: Check time range
        run: |
          # Get the current hour in UTC
          HOUR=$(date +"%H")
          
          # Check if outside 8 AM to 10 PM UTC range
          if [ $HOUR -lt 8 ] || [ $HOUR -gt 22 ]; then
            echo "Current time is outside the schedule range. Exiting..."
            exit 0
          fi
          
          # If within range, the steps below will run

      # - name: Call Callee Workflow
      #   uses: .github/workflows/target.yml
      #   with:
      #     param1: "Hello"
      #     param2: "World"

  call-callee:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Trigger Callee Workflow for Each JSON Item
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          jq -c '.[]' .github/input_parameter.json | while read i; do
            TYPE=$(echo $i | jq -r '.type')
            ENCODED_HOUSE_NAME=$(echo $i | jq -r '.encodedHouseName')
            HOUSE_NAME=$(echo $i | jq -r '.houseName')
            GREP_KEY=$(echo $i | jq -r '.grepKey')
            
            # Use GitHub API to trigger the workflow_dispatch event
            curl \
              -X POST \
              -H "Authorization: token $GITHUB_TOKEN" \
              -H "Accept: application/vnd.github.v3+json" \
              https://api.github.com/repos/${{ github.repository }}/actions/workflows/target2.yml/dispatches \
              -d '{"ref":"main", "inputs": {"type":"'"$TYPE"'", "houseName":"'"$HOUSE_NAME"'", "encodedHouseName":"'"$ENCODED_HOUSE_NAME"'", "grepKey":"'"$GREP_KEY"'"}}'
          done


  # call_reusable_workflow:
  #   uses: ./.github/workflows/target.yml@main
  #   with:
  #     name: "John Doe"
  #     age: 30
  #   secrets:
  #     token: ${{ secrets.GITHUB_TOKEN }}

